### ISSUE TITLE
How do we use this?

### ISSUE THREAD

**Issue by DealsBeam** [plushmonkey/nullspace#1]
As a Subspace Continuum player, how exactly do I use this client to play? I'm on Windows 11.

**Comment by plushmonkey** [comment]
You won't be able to use the client to connect to the normal SSC zones because I can't release the Continuum encryption version. I added more info to the readme to describe the situation better with some instructions for connecting to VIE zones if you want to test it out.

**Comment by DealsBeam** [comment]
Thank you for the prompt reply and help.

I wish more developers just assisted on this project than trying to work on their own which just leads them to being in development hell.

Please put a donation link so we can assist in that way.

**Comment by plushmonkey** [comment]
I would imagine most developers of other projects are doing so just for entertainment. I did most of the work on this in 2021 when I was bored and I've barely worked on it since then. I don't have any plans on actually accomplishing anything with it; it was just for fun and as a reference implementation for anyone stuck on any aspects of the game implementation.

If my goal, or any other developer's goal, was to actually make a viable new client, they all could have just worked on an existing one that was far along. There were a bunch before this and will probably be more after. These projects will always be laying around if anyone actually has a goal of finishing rather than just entertainment.
